aodncore/pipeline/watch.py

Add task_name to log message returned when task is submitted. Add a log line for when an existing file is submitted (e.g. after a service restart).
https://github.com/aodn/zzz-aodn-pipeline-poc/issues/148

Update task submission logging to provide additional info

---

setup.py

This should have been in the previous PR...

Remove dummy entry point from setup.py (breaks tests in aodndata)

---

aodncore/pipeline/exceptions.py
aodncore/pipeline/steps/harvest.py
aodncore/testlib/conf/trigger.conf
aodncore/util/misc.py
test_aodncore/pipeline/steps/test_harvest.py
test_aodncore/pipeline/test_configlib.py
test_aodncore/util/test_misc.py

Fixes https://github.com/aodn/python-aodncore/issues/46
This will obviously need some testing in PO box and RC before being accepted for prod.
The key differences are:
* the various "harvester map" dicts have been consolidated into the same structure for consistency
* Similar to the Ruby trigger script, there is now an additional layer in the looping, essentially a "for each event"
It would be nice to revisit with a refactor to get rid of some code duplication (for example between the run_* methods) but I didn't want to change to much at once.
In addition, this obviously makes the undo scenarios more complicated, so we should revisit that at some point, maybe in combination with the refactor I mentioned above. Probably should be a bit less "procedural", which is what I was getting at when …

Harvester extra params

---

aodncore/pipeline/storage.py
test_aodncore/pipeline/test_storage.py

Fixes bug which threw an exception when receiving an empty result from a storage query. The dict response does not contain a 'Contents' key at all, which wasn't handled.

Update S3 storage broker to correctly handle zero query results

---

aodncore/pipeline/steps/resolve.py

Fix bug with manifest file handling by not popping the value out of the dictionary. Add a couple of optimisations for large rsync manifest files.
This overlaps with the following issue regarding config mutability: https://github.com/aodn/python-aodncore/issues/69

Resolve step fixes

---

requirements.txt

~~DO NOT MERGE until the chef code used to pin the checker version has been removed.~~
This simply updates the requirements file to specify the latest version of the compliance checker, and the imos plugin.

Upgrade to compliance checker 4

---

aodncore/pipeline/handlerbase.py
aodncore/pipeline/schema.py
aodncore/util/__init__.py
aodncore/util/misc.py
test_aodncore/pipeline/test_dummyHandler.py
test_aodncore/util/test_misc.py

Replace **kwargs with custom_params to make handler parameters more strict.
This will prevent the following issue https://github.com/aodn/chef-private/pull/2813/files, where a parameter changed name, but the old name still being accepted and ignored (which was not the expectation!).
This also freezes the params so they can't be corrupted, as happened here: https://github.com/aodn/python-aodncore/commit/bea2fa59a30bb8d61cf19a177a901cbd5b088883#diff-874a2f1726acecf44483414552b613b5

Custom params

---

aodncore/pipeline/fileclassifier.py
test_aodncore/pipeline/test_fileclassifier.py

This was done in data-services (https://github.com/aodn/data-services/pull/740/commits/94c5563115cd063a54221fff0794be8e901567be) after we moved FileClassifier into aodncore.
It is needed for ABOS_SOTS pipeline2.

add option to parse an attribute as a timestamp in FileClassifier

---

aodncore/pipeline/schema.py
aodncore/pipeline/steps/check.py
test_aodncore/pipeline/steps/test_check.py

This is needed right now in order to allow skipping a few annoying checks in some pipelines.
It's related to #97, but is a smaller, simpler change that doesn't require updating all the existing watch configs.

Add skip_checks option to check_params

---

aodncore/pipeline/exceptions.py
aodncore/pipeline/files.py
aodncore/pipeline/handlerbase.py
test_aodncore/pipeline/test_dummyHandler.py
test_aodncore/pipeline/test_files.py

Following on from: https://github.com/aodn/python-aodndata/pull/46
This allows handlers to be configured to exit with an error before publishing anything with an invalid dest_path, as determined by the handler parameters.
For example, Argo would be configured as follows:
```python
handler = ArgoHandler(input_file, allowed_dest_path_regexes=['IMOS/Argo'])
```
Then if, for any reason(e.g. a bug) manages to generate a dest_path outside of 'IMOS/Argo', the handler will error out before publishing anything (i.e. harvesters/uploads/deletions only happen if *every* file matches one of the given regexes).

Add ablility to validate dest_path/archive_path before the handler performs any destructive actions

---

aodncore/pipeline/common.py
aodncore/pipeline/steps/check.py
aodncore/pipeline/steps/resolve.py
aodncore/util/__init__.py
aodncore/util/fileops.py
test_aodncore/pipeline/steps/test_check.py
test_aodncore/pipeline/test_common.py

This allows multiple extensions to correspond with a single FileType enum member.
The primary change is that the "extension" attribute of the enum members has changed from a string to a tuple of valid extensions for a given type. Additionally, the comparison is now case-insensitive, which means for example jpg, jpeg, JPG and JPEG will all be interpreted as a `FileType.JPEG`.
Since this is no longer a one-to-one mapping between extension and type, it's no longer possible to return a single extension from a type, but a) I couldn't find any code doing this and b) if this is required for some reason, it could be a convention to use the *first* extension as a default or preferred option. Hard to envisage anything wanting to do this though, but is hypothetically possible.
I couldn't see …

Filetype multiple extensions

---

aodncore/pipeline/handlerbase.py
test_aodncore/pipeline/test_dummyHandler.py

When this lazy property was migrated to the new decorated style, it retained the old manual lazy pattern code in the body, rather than just returning the object and letting the decorator handle the laziness.

Fix HandlerBase.state_query lazy property

---

aodncore/pipeline/storage.py
test_aodncore/pipeline/test_storage.py

Update list of retried exceptions to include recently occurring ones from logs. Enhance tests to better cover this retrying logic.
```
tasks.ACORN.log:2018-10-22 20:05:29,021 ERROR tasks.ACORN[c2a8103e-55af-4c54-b7ae-3e1dbe0a6af1] StorageBrokerError: error querying storage: SSLError: ('The read operation timed out',)
tasks.ACORN.log:StorageBrokerError: error querying storage: SSLError: ('The read operation timed out',)
tasks.ACORN.log:2018-10-31 15:52:09,739 ERROR tasks.ACORN[3e9f05ff-a878-4239-93de-0a77c0de16d5] StorageBrokerError: error querying storage: SSLError: ('The read operation timed out',)
tasks.ACORN.log:StorageBrokerError: error querying storage: SSLError: ('The read operation timed out',)
tasks.ACORN.log:2019-02-03 15:49:47,056 ERROR …
```

S3 retry update

---

aodncore/pipeline/watch.py

When accessing dict items using str.format, the key should *not* be quoted.
This caused legitimate configuration warnings to be hidden by a useless KeyError.

Fix bug causing handler configuration warnings to be hidden

---

Dockerfile

Not essential for builds, but added for consistency with other Dockerfiles, and makes offline Docker containers more friendly.

Add PATH to Dockerfile

---

setup.py

More unpinning required: OWSLib is currently inconsistent with the [pipeline_requirements.txt](https://github.com/aodn/chef/blob/master/cookbooks/imos_po/files/default/pipeline_requirements.txt#L6) file in chef and therefore breaking all the pipelines :(

unpin version of owslib in setup.py

---

Dockerfile

Fixes the following issue when Jenkins attempts to release the docs: 
```
Theme error:
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)
Makefile:39: recipe for target 'html' failed
make: *** [html] Error 2
```

Add sphinx_rtd_theme to Dockerfile

---

setup.py

The upstream botocore issue has now been resolved, so this temporary pinning should be safe to remove now.

Unpin python-dateutil due to upstream issue being resolved

---

.coveragerc
.travis.yml
Jenkinsfile
setup.py
test_requirements.txt

* Unpin explicit version requirements (except for compliance-checker due to code compatibility, to revisit later)
* Remove requirements that are installed by a dependency (e.g. by compliance-checker already requires OWSLib and tabulate for example)
* Consolidate test requirements to simplify setup of test environments

Unpin requirements in setup.py. Add test_requirements.txt file.

---

constraints.txt

netCDF4 1.5.4 has dropped support for Python 3.5.

Pin netCDF4 to <1.5.4 to continue working correctly on Xenial

---

aodncore/pipeline/schema.py
aodncore/testlib/conf/pipeline.conf
test_aodncore/pipeline/test_configlib.py

Fixes a bug where it was not possible to supply the optional SMTP port configuration item in the pipeline.conf file, due to being missing from the schema definition.

Add `smtp_port` to pipeline.conf jsonschema

---

aodncore/pipeline/schema.py
aodncore/pipeline/steps/resolve.py
aodncore/testlib/dummyhandler.py
test_aodncore/pipeline/steps/test_resolve.py
test_aodncore/pipeline/test_dummyHandler.py

This feature requires that a pipeline(or handler) explicitly allows delete_manifests before resolving them, by setting the flag in the `resolve_params` dictionary.

Add 'allow_delete_manifests' flag to resolve_params

---

.bumpversion.cfg
aodncore/pipeline/files.py
aodncore/pipeline/steps/resolve.py
aodncore/version.py
setup.py

I tried to update some of the moorings handlers in aodndata to work with this. It failed when I tried to add an existing URL (not local path) as a deletion, like this (code is [here](https://github.com/aodn/python-aodndata/pull/249/files#diff-09a7042ec760bab6b4b934a62de7068a07696c16998aa211be9c01a5b443ee1dR359), but now updated):
```python
self.add_to_collection(old_product_url, dest_path=old_product_url,
is_deletion=True, late_deletion=True,
publish_type=PipelineFilePublishType.DELETE_UNHARVEST)
```
I specified it as `is_deletion`, because that's what the arg is called everywhere, _except_ `PipelineFileCollection.add()`, which was calling it `deletion`. So let's make it consistent.
And while I'm at it, let's bump the version number?

Broker refactor - final tweak

---

.bumpversion.cfg
aodncore/pipeline/files.py
aodncore/pipeline/handlerbase.py
aodncore/pipeline/statequery.py
aodncore/pipeline/steps/resolve.py
aodncore/util/wfs.py
aodncore/version.py
setup.py
test_aodncore/pipeline/test_dummyHandler.py
test_aodncore/pipeline/test_files.py
test_aodncore/pipeline/test_statequery.py
test_aodncore/testdata/wfs/GetFeature_filtered.json
test_aodncore/util/test_wfs.py

Following on from https://github.com/aodn/python-aodncore/pull/208
This is how the above PR should have been implemented. The `StateQuery` instance represents the high level "public" interface to any existing state. This provides clarity to child handlers by providing a single "API".
* child handlers can access the resources they need in a simple and consistent way
* breaking changes to aodncore are less likely, since we don't have to worry about a bunch of different edge cases of handlers importing low level objects, and we can maintain and extend this API as appropriate
In addition, to reduce boilerplate in aodndata when adding custom files after input file resolution (e.g. products), PipelineFile's check_type and publish_type attributes may be set during initialisation time and a …

Refactor StateQuery to provide download methods for child handlers

---

Dockerfile
Jenkinsfile

This allows bind mounts the docker socket inside the running container, which allow your tests run docker.
NOTE: This is really bad security practice but it will get you going for now.

Wsd testbuild

---

aodncore/pipeline/steps/harvest.py
test_aodncore/pipeline/steps/test_harvest.py
test_aodncore/testdata/test.recursive_harvest_params

The existing method `build_runsheet` has been modified to:
* iterate over `pipeline_files` instead of `db_objects`
* flag `db_objects[object]` as included if it meets the mapping criteria
* append to list of pipeline files without a matching db_object (table) - for later exception raising (this removes the need to compare each pipeline file against the runsheet)  
The new method `build_dependency_tree` has been added:
* create a new `db_object` with recursive dependencies
I've unit tested this to 3 recursions, but haven't tested in an actual pipeline - the previous commit is an alternative solution based on my original proof of concept, but I think the latest commit is a bit more elegant

Build runsheet with recursive dependencies

---

aodncore/pipeline/handlerbase.py
aodncore/pipeline/steps/harvest.py
sphinx/handler.md
sphinx/userdoc.rst

Updated the readthedocs documentation to include references to generic csv harvester - https://github.com/aodn/backlog/issues/3761
_Note: I couldn't get the aodncore documentation to generate a toctree locally, even though I didn't change the reference in the __modules.rst__ file so I'm wondering whether this is part of the deploy script?_
_Also note: the doco version is sourced from `aodncore.version.\_\_version\_\_` which is now set to `0.0.0` - so this will need to be fixed prior to generating the docs - however the document generation stage (in the Jenkinsfile) is currently commented out pending a different issue https://github.com/aodn/backlog/issues/3684)_

Add generic csv harvester references to docs

---

aodncore/pipeline/watch.py
aodncore/util/__init__.py
aodncore/util/fileops.py
test_aodncore/util/test_fileops.py

Backlog: https://github.com/aodn/backlog/issues/4308
In case there is a misconfigured directory (as per this issue: https://github.com/aodn/issues/issues/1257) this prevents the watch service from failing to start by just skipping the directory and logging a warning which could then be picked up elsewhere e.g. sumo logic

watch service ignore non-existent directories

---

constraints.txt
setup.py

This is not the ideal place to have such a strict constraint, but for now it's the easiest way to avoid [bugs in compliance-checker 5.0.2](https://github.com/aodn/PO-Backlog/issues/3092#issuecomment-1324584772) that can incorrectly fail many of our files.
Also cleaned up a couple of references to Python versions < 3.8 that are no longer relevant.

Pin required compliance-checker version

---

aodncore/pipeline/handlerbase.py
aodncore/pipeline/watch.py

... and only if incoming file has been successfully copied to the landing bucket.
Allows specific legacy pipelines to continue harvesting to the database while forwarding the files to Prefect for publishing to S3.
This is to support the gradual migration of legacy pipelines to Prefect. 
See https://github.com/aodn/backlog/issues/6241

Set default publish type to HARVEST_ONLY when configured

---

aodncore/pipeline/watch.py

First commit: fix a small logic error that made it look like the copy to landing was always successful (even if it wasn't -- this error was introduced in https://github.com/aodn/python-aodncore/pull/280).
Second commit: just clean up the logging a bit.

Fix copy to landing logic
